Opengnsys\ServerBundle\Entity\Repository:
    exclusion_policy: ALL
    properties:
        name:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: name
        ip:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: ip
        description:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: description
        randomId:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: randomId
        secret:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: secret
        id:
            groups: [opengnsys_server__repository_get, opengnsys_server__repository_cget]
            expose: true
            serialized_name: id